// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a manual implementation to avoid protoc dependency

package transport

import (
	"context"

	"google.golang.org/grpc"
)

// VoteRequest is the request for RequestVote RPC
type VoteRequest struct {
	Term         uint64
	CandidateId  string
	LastLogIndex uint64
	LastLogTerm  uint64
}

// VoteResponse is the response for RequestVote RPC
type VoteResponse struct {
	Term        uint64
	VoteGranted bool
}

// LogEntry represents a log entry in AppendEntries
type LogEntry struct {
	Index   uint64
	Term    uint64
	Type    int32
	Command []byte
}

// AppendEntriesRequest is the request for AppendEntries RPC
type AppendEntriesRequest struct {
	Term         uint64
	LeaderId     string
	PrevLogIndex uint64
	PrevLogTerm  uint64
	Entries      []*LogEntry
	LeaderCommit uint64
}

// AppendEntriesResponse is the response for AppendEntries RPC
type AppendEntriesResponse struct {
	Term    uint64
	Success bool
}

// RaftInternalClient is the client interface for RaftInternal service
type RaftInternalClient interface {
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type raftInternalClient struct {
	cc grpc.ClientConnInterface
}

// NewRaftInternalClient creates a new RaftInternal client
func NewRaftInternalClient(cc grpc.ClientConnInterface) RaftInternalClient {
	return &raftInternalClient{cc}
}

func (c *raftInternalClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, "/skylock.RaftInternal/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, "/skylock.RaftInternal/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftInternalServer is the server interface for RaftInternal service
type RaftInternalServer interface {
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
}

// UnimplementedRaftInternalServer is embedded for forward compatibility
type UnimplementedRaftInternalServer struct{}

func (UnimplementedRaftInternalServer) RequestVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, nil
}

func (UnimplementedRaftInternalServer) AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, nil
}

// RegisterRaftInternalServer registers the RaftInternal service
func RegisterRaftInternalServer(s *grpc.Server, srv RaftInternalServer) {
	s.RegisterService(&RaftInternal_ServiceDesc, srv)
}

// RaftInternal_ServiceDesc is the grpc.ServiceDesc for RaftInternal service
var RaftInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skylock.RaftInternal",
	HandlerType: (*RaftInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RaftInternal_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _RaftInternal_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skylock.proto",
}

func _RaftInternal_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skylock.RaftInternal/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skylock.RaftInternal/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}
